site_name: Mangum
site_description: AWS Lambda & API Gateway support for ASGI
site_url: http://mangum.io/

theme:
    name: 'material'
    palette:
      primary: 'brown'
      accent: 'orange'

repo_name: erm/mangum
repo_url: https://github.com/erm/mangum
edit_uri: ""

nav:
    - Introduction: 'index.md'
    - HTTP: 'http.md'
    - WebSockets: 'websockets.md'
    - ASGI: 'asgi.md'

markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: false

