site_name: Mangum
site_description: AWS Lambda & API Gateway support for ASGI
site_url: http://mangum.io/

theme:
    name: 'material'
    palette:
      primary: 'brown'
      accent: 'orange'

repo_name: erm/mangum
repo_url: https://github.com/erm/mangum
edit_uri: ""

nav:
    - Introduction: 'index.md'
    - Adapter: 'adapter.md'
    - HTTP: 'http.md'
    - WebSockets: 'websockets.md'
    - Lifespan: 'lifespan.md'
    - ASGI Frameworks: 'asgi-frameworks.md'
    # - External Links: 'external-links.md' todo
    - Release Notes: 'release-notes.md'

markdown_extensions:
  - mkautodoc
  - markdown.extensions.codehilite:
      guess_lang: false
